### PR TITLE
proximity API

### LINKED ISSUE #29: Create .md and fill content for proximity api

### PR DESCRIPTION
**Pull request by dougaitken**
Added information about the Proximity API, closes #29

### CODE REVIEW

**Comment by dougaitken** [comment]
Changes instances of api / Api -> API for correct stylisation.

**Comment by BPScott** [comment]
Hi @dougaitken, thanks for the PR! It mostly looks good, but can you please provide better link description for the we all love apis link, it's currently "Describe the link please :)"

**Comment by dougaitken** [comment]
Haha aw man! Can't believe I missed that, will amend now

**Comment by dougaitken** [comment]
:shipit:

**Comment by BPScott** [comment]
Boom.

**Pull request merged**
