### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by jonathan-fielding**
Just wanted to add some tweaks to the Readme with the aim of making contributing more easy

### CODE REVIEW

**Comment by BPScott** [comment]
Thanks Jon, The readme updates at the top look good.

Can you please update the useful links to use [repo relative links](https://github.com/blog/1395-relative-links-in-markup-files) and rebase those changes onto this commit (see #50 for an example of this).

**Comment by jonathan-fielding** [comment]
Hey @BPScott 

Just done the changes, 

Thanks
Jonathna

**Comment by BPScott** [comment]
@jonathan-fielding, can you squash these commits down into a single one. I'd like to try and reduce the amount of noise in the commit history. 4 commits for a 13 line readme change feels a bit much :)

**Comment by jonathan-fielding** [comment]
@BPScott squashed 😀

**Pull request merged**
