### PR TITLE
Add CODEOFCONDUCT.md

### LINKED ISSUE #26: Add a code of conduct
I use http://contributor-covenant.org for most of my repositories 🙇

### PR DESCRIPTION
**Pull request by varjmes**
:speak_no_evil: 

Closes #26

### CODE REVIEW

**Comment by andrew** [comment]
@Rumyra is it ok if @Charlotteis puts your email in `[INSERT EMAIL ADDRESS]`?

**Comment by varjmes** [comment]
Wasn't sure which one to add there, thanks Andrew for raising it :)

**Comment by Rumyra** [comment]
Yeh I'll totally do it now :)

**Comment by varjmes** [comment]
:clap: yay

**Pull request merged**
